# Edit these IPs/hostnames to match your EC2 instances.
# Use `ansible_user=ubuntu` for Ubuntu AMIs or `ec2-user` for Amazon Linux.

[web]
frontend ansible_host=54.234.172.89 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/buildersnetwork.pem

[api]
backend  ansible_host=54.196.91.60 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/buildersnetwork.pem

[db]
database ansible_host=3.81.124.168 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/buildersnetwork.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
