---
- name: Pull web image
  community.docker.docker_image:
    name: "{{ web_image }}"
    source: pull
    force_source: true

- name: Run web container
  community.docker.docker_container:
    name: "{{ app_name }}-web"
    image: "{{ web_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
