import path from "node:path";
import { loadConfig } from "@myapp/config";
import { runMigrations } from "@myapp/db";

/**
 * One-shot migration runner for the libSQL/SQLite target (a local file, or a
 * remote Turso database). Run as a separate deploy step (Fly release command,
 * Railway/Render predeploy, Cloud Run Job) — not on app startup.
 *
 * The Cloudflare Worker's D1 database is *not* migrated from here; use
 * `wrangler d1 migrations apply` (see deploy/docs/DEPLOY_CLOUDFLARE.md).
 *
 * SQL migration files are generated by `pnpm db:generate` and copied into the
 * image at `/app/migrations`. Override the location with MIGRATIONS_DIR.
 */
const config = loadConfig();
const migrationsFolder =
  process.env.MIGRATIONS_DIR ?? path.resolve(process.cwd(), "migrations");

console.log(`Running migrations from ${migrationsFolder} ...`);
await runMigrations(config.DATABASE_URL, migrationsFolder, {
  authToken: config.DATABASE_AUTH_TOKEN,
});
console.log("Migrations complete.");
